### ISSUE TITLE
Error in multiple ViewModels with PropertyChanged.Fody

### ISSUE THREAD

**Issue by ccgould** [Wouterdek/NodeNetwork#11] opened 2018-11-04 05:12 UTC
With property changed fody the CodePreviewViewModel causes this error:

MethodAccessException: Attempt by method 'SodeEditorWPFUI.ViewModels.CodePreviewViewModel.set_Code(SodeEditorWPFUI.Models.Compiler.IStatement)' to access method 'ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(System.ComponentModel.PropertyChangedEventArgs)' failed.

I was able to get past this error by placing [DoNotNotify] on top of the class

**Comment by ccgould** [comment] 2018-11-04 19:52
This causes a problem with refreshing the nodes tho

**Comment by Wouterdek** [comment] 2018-11-05 10:28
It seems you have copied and modified the example code. I can't really investigate this without a reproducible example. Could you upload your code?

**Comment by ccgould** [comment] 2018-11-05 13:50
I tried it in the demo project as well if you install the new propertychanged.fody it crashes

**Comment by ccgould** [comment] 2018-11-05 14:14
![image](https://user-images.githubusercontent.com/19482591/48002984-20f22580-e0db-11e8-8e45-84c884dcd345.png)

**Comment by ccgould** [comment] 2018-11-05 14:15
![image](https://user-images.githubusercontent.com/19482591/48003029-42531180-e0db-11e8-9ad7-457dd25bbc8c.png)

**Comment by ccgould** [comment] 2018-11-06 22:39
Yea it is a Fody and ReactiveUI issue. When I used ReactiveUI.Fody I lost my property changed functionality did yours work or is there an extra step I am not familiar with ReactiveUI that much

**Comment by Wouterdek** [comment] 2018-11-07 13:12
It worked fine for me after following the guide on the github page: https://github.com/kswoll/ReactiveUI.Fody/blob/rxui7beta/Readme.md

I am closing this issue because it is not related to NodeNetwork, but rather to Fody/ReactiveUI

**Closed by Wouterdek** 2018-11-07 13:12 UTC

**Comment by ccgould** [comment] 2018-11-07 13:13
Ok ill give it a try
