### ISSUE TITLE
Sometimes ports get cut in half

### ISSUE THREAD

**Issue by KayakSnail** [Wouterdek/NodeNetwork#41] opened 2019-07-24 19:56 UTC
The node port connectors sometimes get cut in half depending on the size of the node:
![image](https://user-images.githubusercontent.com/53276157/61824092-10dec980-ae55-11e9-89ad-43cc95c41d94.png)
sometimes not:
![image](https://user-images.githubusercontent.com/53276157/61824159-38ce2d00-ae55-11e9-8147-dd1361dfbe75.png)

It even occurs when connected:
![image](https://user-images.githubusercontent.com/53276157/61824222-5f8c6380-ae55-11e9-8a68-65334260ff0f.png)

**Comment by Wouterdek** [comment] 2019-07-25 08:12
I can't seem to reproduce this. Would it be possible for you to create a minimal, reproducable example? ([info](https://stackoverflow.com/help/minimal-reproducible-example))

**Comment by KayakSnail** [comment] 2019-07-25 13:59
I'll try. If not I could send you the project I have?

**Comment by Wouterdek** [comment] 2019-07-25 14:47
Sure

**Comment by KayakSnail** [comment] 2019-07-30 09:18
I've sent you the project  via proofpoint.

**Comment by Wouterdek** [comment] 2019-08-09 12:46
How do I access that?

**Comment by KayakSnail** [comment] 2019-08-09 19:44
Did you get the invite to your email? It would have been sent from my work email.

**Comment by Wouterdek** [comment] 2019-08-10 13:58
Ah, found it. The mail was in the spam folder. Thanks.

**Comment by Wouterdek** [comment] 2019-10-01 11:53
Ok so this seems to be a weird WPF bug that is caused by floating point weirdness when the height takes on certain values. I changed the margins on the port and that seems to fix it. Let me know if it isn't fixed by the next commit.

**Closed** 2019-10-01 11:54 UTC
Labels: bug

**Comment by KayakSnail** [comment] 2019-10-11 11:59
Fix confirmed:
![image](https://user-images.githubusercontent.com/53276157/66649762-e23be800-ec26-11e9-9be0-c33279d3a967.png)
